### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by kYuZz** [nikvdp/pidcrypt#5]
To reproduce, create an empty file and save it with the name `index.js`:

```javascript
require('pidcrypt/seedrandom')
const pidCrypt = require('pidcrypt')
require('pidcrypt/rsa')
```

Running `node index.js` outputs this error:

```
node_modules/pidcrypt/jsbn.js:100
if(j_lm && (navigator.appName == "Microsoft Internet Explorer")) {
            ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/home/kyuzz/Projects/test-ig-api/node_modules/pidcrypt/jsbn.js:100:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kyuzz/Projects/test-ig-api/node_modules/pidcrypt/rsa.js:63:18)
    at Module._compile (module.js:556:32)
```

**Comment by rabbitlair** [comment]
Same here, I have the exact same error when using last pidCrypt version.

**Comment by kambajwa** [comment]
same issue here, any updates ??

**Comment by kambajwa** [comment]
Any updates on this issue ??

**Comment by joseSantacruz** [comment]
any update???

**Comment by kambajwa** [comment]
@joseSantacruz sorry, i'haven't received any updates either but i comment out the 

> _&& (navigator.appName == "Microsoft Internet Explorer")_
   or you can always use 
> _navigator = {appName:'VM'};_

 as a temporary fix until you have any thing..

**Comment by kevinkga** [comment]
It'd be quite easy to fix. I wonder why nobody has bothered? Just swap the following lines
https://github.com/nikvdp/pidcrypt/blob/cc2b10a88132564945bca68b30b07006491c6898/jsbn.js#L100
with
``
if(j_lm && typeof navigator !== 'undefined' && (navigator.appName == "Microsoft Internet Explorer")) {
  BigInteger.prototype.am = am2;
  dbits = 30;
}
else if(j_lm && typeof navigator !== 'undefined' && (navigator.appName != "Netscape")) {
  BigInteger.prototype.am = am1;
  dbits = 26;
}

**Comment by ChristophDietrich** [comment]
Please make all forkers a happy day, do an update here ;) 

Would be awesome! @nikvdp

**Comment by nikvdp** [comment]
merged!

**Comment by esellin** [comment]
A new version published on NPM would be awesome!

**Comment by kea0811** [comment]
@nikvdp hello, will you consider to published the merge version in npm?

**Comment by nikvdp** [comment]
@kea0811 @esellin published!
